from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")  # Replace with your MongoDB URI if needed
db = client["student_accomodation"]  # Database name
hostel_collection = db["hostels"]  # Collection name

# Remaining hostel data to insert
hostels = [
    {
        "id": 1,
        "hostel_name": "Ruby Hostel",
        "vacancy": 23,
        "amenities": [
            "wifi",
            "fitness centre",
            "fridge",
            "furniture",
            "ac"
        ],
        "address": "1, Tambaram",
        "hostel_owner": "Suresh",
        "contact_no": "7570599623",
        "nearby_university": "Madras University",
        "location": "Teynampet",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 6071,
        "distance": 1750
    },
    {
        "id": 2,
        "hostel_name": "Rubies Hostel",
        "vacancy": 7,
        "amenities": [
            "laundry",
            "fridge",
            "wifi",
            "furniture",
            "food",
            "ac",
            "study table",
            "kitchen"
        ],
        "address": "30, Kodambakkam",
        "hostel_owner": "Karthik",
        "contact_no": "8157994858",
        "nearby_university": "Madras University",
        "location": "Guindy",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9653,
        "distance": 1711
    },
    {
        "id": 3,
        "hostel_name": "Sapphires Hostel",
        "vacancy": 5,
        "amenities": [
            "ac",
            "kitchen",
            "study table",
            "wifi",
            "furniture"
        ],
        "address": "130, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "8388018633",
        "nearby_university": "Madras University",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 7133,
        "distance": 1196
    },
    {
        "id": 4,
        "hostel_name": "Topaz Hostel",
        "vacancy": 24,
        "amenities": [
            "kitchen",
            "furniture",
            "ac",
            "laundry",
            "study table",
            "fitness centre"
        ],
        "address": "174, Kodambakkam",
        "hostel_owner": "Suresh",
        "contact_no": "6219971850",
        "nearby_university": "Madras University",
        "location": "Guindy",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6762,
        "distance": 1533
    },
    {
        "id": 5,
        "hostel_name": "Ruby2 Hostel",
        "vacancy": 12,
        "amenities": [
            "study table",
            "food",
            "laundry",
            "ac",
            "wifi",
            "furniture"
        ],
        "address": "174, Kodambakkam",
        "hostel_owner": "Karthik",
        "contact_no": "8716653546",
        "nearby_university": "Anna University",
        "location": "Guindy",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9990,
        "distance": 1700
    },
    {
        "id": 6,
        "hostel_name": "Topazes Hostel",
        "vacancy": 11,
        "amenities": [
            "ac",
            "kitchen",
            "fridge",
            "food",
            "laundry",
            "wifi"
        ],
        "address": "177, Porur",
        "hostel_owner": "Ramesh",
        "contact_no": "8318189807",
        "nearby_university": "Anna University",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7249,
        "distance": 1720
    },
    {
        "id": 7,
        "hostel_name": "crown Hostel",
        "vacancy": 21,
        "amenities": [
            "fridge",
            "laundry",
            "furniture",
            "ac",
            "kitchen",
            "wifi",
            "food"
        ],
        "address": "4, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "8272036465",
        "nearby_university": "Anna University",
        "location": "Guindy",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5583,
        "distance": 666
    },
    {
        "id": 8,
        "hostel_name": "tres Hostel",
        "vacancy": 25,
        "amenities": [
            "fridge",
            "study table",
            "kitchen",
            "furniture",
            "fitness centre",
            "food",
            "laundry",
            "ac"
        ],
        "address": "69, Velachery",
        "hostel_owner": "Priya",
        "contact_no": "9421784979",
        "nearby_university": "Anna University",
        "location": "Porur",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 7707,
        "distance": 715
    },
    {
        "id": 9,
        "hostel_name": "citylink Hostel",
        "vacancy": 8,
        "amenities": [
            "fitness centre",
            "laundry",
            "kitchen",
            "study table",
            "furniture",
            "fridge",
            "food",
            "ac"
        ],
        "address": "121, Porur",
        "hostel_owner": "Ramesh",
        "contact_no": "8128509242",
        "nearby_university": "SRM Institute of Science and Technology",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 5213,
        "distance": 740
    },
    {
        "id": 10,
        "hostel_name": "sunrise Hostel",
        "vacancy": 20,
        "amenities": [
            "furniture",
            "fitness centre",
            "ac",
            "fridge",
            "laundry",
            "kitchen"
        ],
        "address": "60, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "6358949017",
        "nearby_university": "SRM Institute of Science and Technology",
        "location": "Porur",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 8512,
        "distance": 1210
    },
    {
        "id": 11,
        "hostel_name": "Pearl Hostel",
        "vacancy": 17,
        "amenities": [
            "ac",
            "kitchen",
            "food",
            "wifi",
            "fitness centre"
        ],
        "address": "56, Saidapet",
        "hostel_owner": "Priya",
        "contact_no": "6545971189",
        "nearby_university": "SRM Institute of Science and Technology",
        "location": "Guindy",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 7516,
        "distance": 1443
    },
    {
        "id": 12,
        "hostel_name": "serenity Hostel",
        "vacancy": 15,
        "amenities": [
            "fridge",
            "ac",
            "furniture",
            "food"
        ],
        "address": "98, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "9903673438",
        "nearby_university": "SRM Institute of Science and Technology",
        "location": "Velachery",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 9794,
        "distance": 1050
    },
    {
        "id": 13,
        "hostel_name": "cozy corner Hostel",
        "vacancy": 7,
        "amenities": [
            "study table",
            "laundry",
            "kitchen",
            "food",
            "ac"
        ],
        "address": "123, Kodambakkam",
        "hostel_owner": "Karthik",
        "contact_no": "6430240250",
        "nearby_university": "Sathyabama University",
        "location": "Porur",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 5453,
        "distance": 763
    },
    {
        "id": 14,
        "hostel_name": "hosrizon Hostel",
        "vacancy": 23,
        "amenities": [
            "furniture",
            "study table",
            "fridge",
            "laundry"
        ],
        "address": "30, Guindy",
        "hostel_owner": "Suresh",
        "contact_no": "9975772131",
        "nearby_university": "Sathyabama University",
        "location": "Velachery",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 6744,
        "distance": 827
    },
    {
        "id": 15,
        "hostel_name": "zen zone Hostel",
        "vacancy": 25,
        "amenities": [
            "wifi",
            "fitness centre",
            "furniture",
            "laundry",
            "food",
            "fridge",
            "kitchen",
            "ac"
        ],
        "address": "25, Tambaram",
        "hostel_owner": "Suresh",
        "contact_no": "7179593320",
        "nearby_university": "Sathyabama University",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 6035,
        "distance": 1787
    },
    {
        "id": 16,
        "hostel_name": "ecostay Hostel",
        "vacancy": 16,
        "amenities": [
            "food",
            "laundry",
            "kitchen",
            "study table",
            "furniture",
            "fitness centre",
            "wifi",
            "ac"
        ],
        "address": "174, Velachery",
        "hostel_owner": "Vikram",
        "contact_no": "9050667495",
        "nearby_university": "Sathyabama University",
        "location": "Adyar",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 7845,
        "distance": 1952
    },
    {
        "id": 17,
        "hostel_name": "chill pad Hostel",
        "vacancy": 10,
        "amenities": [
            "study table",
            "fridge",
            "ac",
            "furniture",
            "laundry"
        ],
        "address": "96, Velachery",
        "hostel_owner": "Suresh",
        "contact_no": "8593126237",
        "nearby_university": "VIT Chennai",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 7749,
        "distance": 990
    },
    {
        "id": 18,
        "hostel_name": "ivy Hostel",
        "vacancy": 9,
        "amenities": [
            "study table",
            "ac",
            "fitness centre",
            "food"
        ],
        "address": "162, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "6495170613",
        "nearby_university": "VIT Chennai",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 9696,
        "distance": 1232
    },
    {
        "id": 19,
        "hostel_name": "maple Hostel",
        "vacancy": 13,
        "amenities": [
            "kitchen",
            "wifi",
            "ac",
            "study table",
            "furniture",
            "laundry",
            "fitness centre",
            "fridge"
        ],
        "address": "77, Velachery",
        "hostel_owner": "Vikram",
        "contact_no": "6547974853",
        "nearby_university": "VIT Chennai",
        "location": "Saidapet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 7235,
        "distance": 1679
    },
    {
        "id": 20,
        "hostel_name": "oakwood Hostel",
        "vacancy": 8,
        "amenities": [
            "laundry",
            "fitness centre",
            "kitchen",
            "food",
            "furniture"
        ],
        "address": "157, Saidapet",
        "hostel_owner": "Ramesh",
        "contact_no": "7924303625",
        "nearby_university": "VIT Chennai",
        "location": "Adyar",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 8769,
        "distance": 1029
    },
    {
        "id": 21,
        "hostel_name": "cityscape Hostel",
        "vacancy": 13,
        "amenities": [
            "food",
            "study table",
            "ac",
            "fridge",
            "furniture",
            "wifi",
            "kitchen"
        ],
        "address": "115, Velachery",
        "hostel_owner": "Suresh",
        "contact_no": "9139653066",
        "nearby_university": "Hindustan Institute of Technology and Science",
        "location": "Teynampet",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 6576,
        "distance": 1005
    },
    {
        "id": 22,
        "hostel_name": "bluebel Hostel",
        "vacancy": 22,
        "amenities": [
            "wifi",
            "food",
            "furniture",
            "fitness centre"
        ],
        "address": "8, Kodambakkam",
        "hostel_owner": "Ramesh",
        "contact_no": "7871161482",
        "nearby_university": "Hindustan Institute of Technology and Science",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 9137,
        "distance": 1548
    },
    {
        "id": 23,
        "hostel_name": "nova Hostel",
        "vacancy": 7,
        "amenities": [
            "furniture",
            "food",
            "study table",
            "kitchen",
            "laundry"
        ],
        "address": "25, Porur",
        "hostel_owner": "Suresh",
        "contact_no": "8459123314",
        "nearby_university": "Hindustan Institute of Technology and Science",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 5667,
        "distance": 1322
    },
    {
        "id": 24,
        "hostel_name": "niche Hostel",
        "vacancy": 23,
        "amenities": [
            "study table",
            "wifi",
            "fridge",
            "laundry",
            "food",
            "ac"
        ],
        "address": "55, Teynampet",
        "hostel_owner": "Karthik",
        "contact_no": "9266142728",
        "nearby_university": "Hindustan Institute of Technology and Science",
        "location": "Porur",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 9662,
        "distance": 786
    },
    {
        "id": 25,
        "hostel_name": "comfort crib Hostel",
        "vacancy": 5,
        "amenities": [
            "food",
            "wifi",
            "laundry",
            "furniture"
        ],
        "address": "63, Adyar",
        "hostel_owner": "Vikram",
        "contact_no": "7049412018",
        "nearby_university": "Saveetha University",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9196,
        "distance": 1404
    },
    {
        "id": 26,
        "hostel_name": "coral Hostel",
        "vacancy": 6,
        "amenities": [
            "wifi",
            "ac",
            "study table",
            "furniture",
            "food",
            "kitchen"
        ],
        "address": "32, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "8349460285",
        "nearby_university": "Saveetha University",
        "location": "Adyar",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7099,
        "distance": 1477
    },
    {
        "id": 27,
        "hostel_name": "cave Hostel",
        "vacancy": 16,
        "amenities": [
            "food",
            "wifi",
            "ac",
            "furniture",
            "fitness centre",
            "kitchen"
        ],
        "address": "136, Teynampet",
        "hostel_owner": "Priya",
        "contact_no": "9798615080",
        "nearby_university": "Saveetha University",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6492,
        "distance": 1342
    },
    {
        "id": 28,
        "hostel_name": "pines Hostel",
        "vacancy": 21,
        "amenities": [
            "study table",
            "wifi",
            "laundry",
            "food",
            "kitchen",
            "fridge",
            "furniture"
        ],
        "address": "85, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "7485211010",
        "nearby_university": "Saveetha University",
        "location": "Teynampet",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 6771,
        "distance": 1201
    },
    {
        "id": 29,
        "hostel_name": "riverstone Hostel",
        "vacancy": 6,
        "amenities": [
            "fitness centre",
            "study table",
            "ac",
            "laundry"
        ],
        "address": "46, Adyar",
        "hostel_owner": "Suresh",
        "contact_no": "9619456636",
        "nearby_university": "Tamil Nadu Dr. M.G.R. Medical University",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 8293,
        "distance": 1814
    },
    {
        "id": 30,
        "hostel_name": "cedar Hostel",
        "vacancy": 5,
        "amenities": [
            "ac",
            "furniture",
            "laundry",
            "fridge",
            "wifi",
            "food",
            "kitchen",
            "study table"
        ],
        "address": "82, Saidapet",
        "hostel_owner": "Vikram",
        "contact_no": "9179293859",
        "nearby_university": "Tamil Nadu Dr. M.G.R. Medical University",
        "location": "Porur",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 8905,
        "distance": 575
    },
    {
        "id": 31,
        "hostel_name": "owl Hostel",
        "vacancy": 12,
        "amenities": [
            "fridge",
            "food",
            "furniture",
            "wifi"
        ],
        "address": "118, Saidapet",
        "hostel_owner": "Vikram",
        "contact_no": "9407574314",
        "nearby_university": "Tamil Nadu Dr. M.G.R. Medical University",
        "location": "Saidapet",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 5053,
        "distance": 1922
    },
    {
        "id": 32,
        "hostel_name": "acacia Hostel",
        "vacancy": 23,
        "amenities": [
            "wifi",
            "furniture",
            "laundry",
            "fitness centre"
        ],
        "address": "37, Kodambakkam",
        "hostel_owner": "Karthik",
        "contact_no": "6698901674",
        "nearby_university": "Tamil Nadu Dr. M.G.R. Medical University",
        "location": "Adyar",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9440,
        "distance": 693
    },
    {
        "id": 33,
        "hostel_name": "adobe Hostel",
        "vacancy": 15,
        "amenities": [
            "furniture",
            "fridge",
            "food",
            "kitchen",
            "laundry",
            "fitness centre"
        ],
        "address": "142, Velachery",
        "hostel_owner": "Ramesh",
        "contact_no": "9296903813",
        "nearby_university": "Vel Tech University",
        "location": "Guindy",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 5906,
        "distance": 1595
    },
    {
        "id": 34,
        "hostel_name": "urbanvibe Hostel",
        "vacancy": 12,
        "amenities": [
            "fitness centre",
            "ac",
            "study table",
            "food",
            "wifi",
            "kitchen",
            "furniture",
            "fridge"
        ],
        "address": "99, Tambaram",
        "hostel_owner": "Priya",
        "contact_no": "9611078636",
        "nearby_university": "Vel Tech University",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 9688,
        "distance": 1552
    },
    {
        "id": 35,
        "hostel_name": "pineview Hostel",
        "vacancy": 22,
        "amenities": [
            "food",
            "fridge",
            "ac",
            "wifi",
            "study table",
            "laundry"
        ],
        "address": "30, Teynampet",
        "hostel_owner": "Priya",
        "contact_no": "8806642346",
        "nearby_university": "Vel Tech University",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 9991,
        "distance": 612
    },
    {
        "id": 36,
        "hostel_name": "ggolden Hostel",
        "vacancy": 15,
        "amenities": [
            "furniture",
            "fitness centre",
            "ac",
            "study table",
            "fridge",
            "kitchen"
        ],
        "address": "129, Adyar",
        "hostel_owner": "Karthik",
        "contact_no": "8614041458",
        "nearby_university": "Vel Tech University",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 8820,
        "distance": 1200
    },
    {
        "id": 37,
        "hostel_name": "diamond Hostel",
        "vacancy": 11,
        "amenities": [
            "fridge",
            "study table",
            "fitness centre",
            "ac",
            "food",
            "kitchen",
            "laundry"
        ],
        "address": "190, Adyar",
        "hostel_owner": "Ramesh",
        "contact_no": "7314956876",
        "nearby_university": "Bharath University",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6150,
        "distance": 1305
    },
    {
        "id": 38,
        "hostel_name": "tranquil Hostel",
        "vacancy": 22,
        "amenities": [
            "laundry",
            "kitchen",
            "fitness centre",
            "ac",
            "wifi",
            "study table",
            "fridge",
            "food"
        ],
        "address": "36, Tambaram",
        "hostel_owner": "Karthik",
        "contact_no": "8393011112",
        "nearby_university": "Bharath University",
        "location": "Guindy",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9925,
        "distance": 1828
    },
    {
        "id": 39,
        "hostel_name": "sleepy owl Hostel",
        "vacancy": 5,
        "amenities": [
            "kitchen",
            "fitness centre",
            "study table",
            "ac",
            "wifi",
            "fridge"
        ],
        "address": "112, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "9707080120",
        "nearby_university": "Bharath University",
        "location": "Guindy",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7931,
        "distance": 1184
    },
    {
        "id": 40,
        "hostel_name": "casa Hostel",
        "vacancy": 12,
        "amenities": [
            "ac",
            "wifi",
            "laundry",
            "furniture"
        ],
        "address": "162, Adyar",
        "hostel_owner": "Karthik",
        "contact_no": "6151013462",
        "nearby_university": "Bharath University",
        "location": "Velachery",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 7680,
        "distance": 615
    },
    {
        "id": 41,
        "hostel_name": "calm Hostel",
        "vacancy": 15,
        "amenities": [
            "wifi",
            "food",
            "ac",
            "kitchen",
            "furniture",
            "fridge",
            "study table"
        ],
        "address": "130, Porur",
        "hostel_owner": "Priya",
        "contact_no": "6321716573",
        "nearby_university": "Loyola College",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 8892,
        "distance": 1645
    },
    {
        "id": 42,
        "hostel_name": "lantern Hostel",
        "vacancy": 7,
        "amenities": [
            "furniture",
            "ac",
            "laundry",
            "wifi",
            "food",
            "fitness centre",
            "study table"
        ],
        "address": "70, Guindy",
        "hostel_owner": "Vikram",
        "contact_no": "6072402495",
        "nearby_university": "Loyola College",
        "location": "Porur",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 9094,
        "distance": 1442
    },
    {
        "id": 43,
        "hostel_name": "hilltop Hostel",
        "vacancy": 24,
        "amenities": [
            "laundry",
            "fitness centre",
            "fridge",
            "study table"
        ],
        "address": "3, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "8540482995",
        "nearby_university": "Loyola College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 8728,
        "distance": 1431
    },
    {
        "id": 44,
        "hostel_name": "luna Hostel",
        "vacancy": 20,
        "amenities": [
            "kitchen",
            "wifi",
            "fridge",
            "laundry",
            "food",
            "study table",
            "fitness centre",
            "furniture"
        ],
        "address": "33, Kodambakkam",
        "hostel_owner": "Ramesh",
        "contact_no": "6406376630",
        "nearby_university": "Loyola College",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6021,
        "distance": 1384
    },
    {
        "id": 45,
        "hostel_name": "casag Hostel",
        "vacancy": 19,
        "amenities": [
            "wifi",
            "study table",
            "kitchen",
            "ac"
        ],
        "address": "162, Tambaram",
        "hostel_owner": "Priya",
        "contact_no": "9658578006",
        "nearby_university": "Stella Maris College",
        "location": "Saidapet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6874,
        "distance": 887
    },
    {
        "id": 46,
        "hostel_name": "mindspace Hostel",
        "vacancy": 19,
        "amenities": [
            "wifi",
            "ac",
            "fitness centre",
            "study table",
            "kitchen",
            "fridge",
            "laundry"
        ],
        "address": "137, Adyar",
        "hostel_owner": "Karthik",
        "contact_no": "8268339355",
        "nearby_university": "Stella Maris College",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 6728,
        "distance": 1421
    },
    {
        "id": 47,
        "hostel_name": "econest Hostel",
        "vacancy": 23,
        "amenities": [
            "fridge",
            "fitness centre",
            "wifi",
            "kitchen",
            "food",
            "furniture"
        ],
        "address": "94, Saidapet",
        "hostel_owner": "Karthik",
        "contact_no": "6528569968",
        "nearby_university": "Stella Maris College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 8889,
        "distance": 1770
    },
    {
        "id": 48,
        "hostel_name": "glimmer Hostel",
        "vacancy": 5,
        "amenities": [
            "study table",
            "fitness centre",
            "kitchen",
            "laundry",
            "ac"
        ],
        "address": "141, Kodambakkam",
        "hostel_owner": "Suresh",
        "contact_no": "7490273424",
        "nearby_university": "Stella Maris College",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 5419,
        "distance": 1827
    },
    {
        "id": 49,
        "hostel_name": "thrive Hostel",
        "vacancy": 11,
        "amenities": [
            "fitness centre",
            "wifi",
            "laundry",
            "fridge",
            "kitchen",
            "food"
        ],
        "address": "182, Adyar",
        "hostel_owner": "Vikram",
        "contact_no": "7696884593",
        "nearby_university": "Ethiraj College for Women",
        "location": "Velachery",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 9151,
        "distance": 557
    },
    {
        "id": 50,
        "hostel_name": "hilltop Hostel",
        "vacancy": 5,
        "amenities": [
            "wifi",
            "fridge",
            "food",
            "kitchen",
            "fitness centre",
            "furniture",
            "laundry",
            "ac"
        ],
        "address": "75, Guindy",
        "hostel_owner": "Ramesh",
        "contact_no": "9986516001",
        "nearby_university": "Ethiraj College for Women",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 5595,
        "distance": 1662
    },
    {
        "id": 51,
        "hostel_name": "ComfortZone Hostel",
        "vacancy": 8,
        "amenities": [
            "fitness centre",
            "fridge",
            "furniture",
            "study table",
            "kitchen",
            "laundry",
            "wifi"
        ],
        "address": "36, Tambaram",
        "hostel_owner": "Ramesh",
        "contact_no": "6121674290",
        "nearby_university": "Ethiraj College for Women",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 9996,
        "distance": 1352
    },
    {
        "id": 52,
        "hostel_name": "HappyHaven Hostel",
        "vacancy": 25,
        "amenities": [
            "fridge",
            "wifi",
            "fitness centre",
            "laundry",
            "furniture",
            "ac"
        ],
        "address": "33, Velachery",
        "hostel_owner": "Karthik",
        "contact_no": "7527873057",
        "nearby_university": "Ethiraj College for Women",
        "location": "Adyar",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 8445,
        "distance": 762
    },
    {
        "id": 53,
        "hostel_name": "HomeRootsl Hostel",
        "vacancy": 15,
        "amenities": [
            "study table",
            "ac",
            "food",
            "kitchen",
            "furniture"
        ],
        "address": "113, Saidapet",
        "hostel_owner": "Vikram",
        "contact_no": "8277985875",
        "nearby_university": "Presidency College",
        "location": "Guindy",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 6391,
        "distance": 1803
    },
    {
        "id": 54,
        "hostel_name": "peacepod Hostel",
        "vacancy": 24,
        "amenities": [
            "fitness centre",
            "study table",
            "kitchen",
            "ac",
            "furniture",
            "fridge"
        ],
        "address": "194, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "7099160641",
        "nearby_university": "Presidency College",
        "location": "Guindy",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 7153,
        "distance": 1333
    },
    {
        "id": 55,
        "hostel_name": "sleepwell Hostel",
        "vacancy": 16,
        "amenities": [
            "wifi",
            "fridge",
            "study table",
            "furniture"
        ],
        "address": "124, Guindy",
        "hostel_owner": "Vikram",
        "contact_no": "7960681618",
        "nearby_university": "Presidency College",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 7447,
        "distance": 618
    },
    {
        "id": 56,
        "hostel_name": "chillpad Hostel",
        "vacancy": 13,
        "amenities": [
            "food",
            "kitchen",
            "ac",
            "fridge",
            "fitness centre",
            "laundry"
        ],
        "address": "109, Velachery",
        "hostel_owner": "Karthik",
        "contact_no": "6262439069",
        "nearby_university": "Presidency College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6235,
        "distance": 1727
    },
    {
        "id": 57,
        "hostel_name": "easystay Hostel",
        "vacancy": 12,
        "amenities": [
            "study table",
            "wifi",
            "fitness centre",
            "kitchen",
            "laundry"
        ],
        "address": "22, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "7991908913",
        "nearby_university": "Guru Nanak College",
        "location": "Adyar",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 6231,
        "distance": 1669
    },
    {
        "id": 58,
        "hostel_name": "nestaway Hostel",
        "vacancy": 11,
        "amenities": [
            "food",
            "wifi",
            "fridge",
            "ac",
            "laundry"
        ],
        "address": "137, Kodambakkam",
        "hostel_owner": "Vikram",
        "contact_no": "6764621497",
        "nearby_university": "Guru Nanak College",
        "location": "Guindy",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 9710,
        "distance": 1076
    },
    {
        "id": 59,
        "hostel_name": "cozynest Hostel",
        "vacancy": 23,
        "amenities": [
            "fitness centre",
            "fridge",
            "ac",
            "furniture",
            "wifi",
            "food",
            "kitchen"
        ],
        "address": "74, Porur",
        "hostel_owner": "Suresh",
        "contact_no": "9268936897",
        "nearby_university": "Guru Nanak College",
        "location": "Adyar",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 5833,
        "distance": 952
    },
    {
        "id": 60,
        "hostel_name": "rosy Hostel",
        "vacancy": 17,
        "amenities": [
            "fitness centre",
            "fridge",
            "food",
            "study table",
            "wifi"
        ],
        "address": "178, Adyar",
        "hostel_owner": "Karthik",
        "contact_no": "8400038485",
        "nearby_university": "Guru Nanak College",
        "location": "Velachery",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 6108,
        "distance": 1762
    },
    {
        "id": 61,
        "hostel_name": "EduHut Hostel",
        "vacancy": 18,
        "amenities": [
            "laundry",
            "fridge",
            "food",
            "study table",
            "furniture",
            "kitchen"
        ],
        "address": "56, Kodambakkam",
        "hostel_owner": "Suresh",
        "contact_no": "9060416024",
        "nearby_university": "Meenakshi College for Women",
        "location": "Guindy",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 9703,
        "distance": 525
    },
    {
        "id": 62,
        "hostel_name": "ScholarStaye Hostel",
        "vacancy": 25,
        "amenities": [
            "wifi",
            "kitchen",
            "fridge",
            "laundry"
        ],
        "address": "177, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "9013759425",
        "nearby_university": "Meenakshi College for Women",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 6154,
        "distance": 618
    },
    {
        "id": 63,
        "hostel_name": "CampusCrib Hostel",
        "vacancy": 5,
        "amenities": [
            "kitchen",
            "fitness centre",
            "laundry",
            "fridge",
            "wifi",
            "ac",
            "food"
        ],
        "address": "31, Tambaram",
        "hostel_owner": "Vikram",
        "contact_no": "9549152034",
        "nearby_university": "Meenakshi College for Women",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 9591,
        "distance": 605
    },
    {
        "id": 64,
        "hostel_name": "LearnLodge Hostel",
        "vacancy": 8,
        "amenities": [
            "fitness centre",
            "fridge",
            "food",
            "furniture",
            "kitchen"
        ],
        "address": "124, Guindy",
        "hostel_owner": "Karthik",
        "contact_no": "7221954075",
        "nearby_university": "Meenakshi College for Women",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 9955,
        "distance": 1505
    },
    {
        "id": 65,
        "hostel_name": "uninest Hostel",
        "vacancy": 5,
        "amenities": [
            "ac",
            "study table",
            "furniture",
            "wifi"
        ],
        "address": "76, Adyar",
        "hostel_owner": "Ramesh",
        "contact_no": "9549681678",
        "nearby_university": "Women's Christian College",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 8969,
        "distance": 1032
    },
    {
        "id": 66,
        "hostel_name": "studystay Hostel",
        "vacancy": 9,
        "amenities": [
            "fridge",
            "ac",
            "fitness centre",
            "study table"
        ],
        "address": "186, Velachery",
        "hostel_owner": "Ramesh",
        "contact_no": "6204192508",
        "nearby_university": "Women's Christian College",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 5464,
        "distance": 854
    },
    {
        "id": 67,
        "hostel_name": "classy Hostel",
        "vacancy": 10,
        "amenities": [
            "wifi",
            "food",
            "study table",
            "ac",
            "fridge",
            "furniture"
        ],
        "address": "185, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "6754480051",
        "nearby_university": "Women's Christian College",
        "location": "Adyar",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6100,
        "distance": 943
    },
    {
        "id": 68,
        "hostel_name": "acad Hostel",
        "vacancy": 11,
        "amenities": [
            "fridge",
            "furniture",
            "food",
            "ac",
            "kitchen",
            "laundry"
        ],
        "address": "122, Saidapet",
        "hostel_owner": "Karthik",
        "contact_no": "6556372959",
        "nearby_university": "Women's Christian College",
        "location": "Porur",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 7503,
        "distance": 959
    },
    {
        "id": 69,
        "hostel_name": "smartrooms Hostel",
        "vacancy": 18,
        "amenities": [
            "kitchen",
            "fridge",
            "furniture",
            "study table",
            "food",
            "fitness centre",
            "ac"
        ],
        "address": "61, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "7179013722",
        "nearby_university": "Madras Christian College",
        "location": "Porur",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5999,
        "distance": 661
    },
    {
        "id": 70,
        "hostel_name": "brainbase Hostel",
        "vacancy": 6,
        "amenities": [
            "food",
            "fitness centre",
            "kitchen",
            "ac",
            "furniture",
            "laundry"
        ],
        "address": "191, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "7884897784",
        "nearby_university": "Madras Christian College",
        "location": "Teynampet",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 9431,
        "distance": 696
    },
    {
        "id": 71,
        "hostel_name": "MetroLodge Hostel",
        "vacancy": 22,
        "amenities": [
            "ac",
            "food",
            "fitness centre",
            "kitchen",
            "laundry"
        ],
        "address": "188, Adyar",
        "hostel_owner": "Ramesh",
        "contact_no": "6115962428",
        "nearby_university": "Madras Christian College",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 9384,
        "distance": 974
    },
    {
        "id": 72,
        "hostel_name": " Cityscape Hostel",
        "vacancy": 21,
        "amenities": [
            "study table",
            "ac",
            "laundry",
            "kitchen",
            "furniture"
        ],
        "address": "196, Porur",
        "hostel_owner": "Suresh",
        "contact_no": "8963759132",
        "nearby_university": "Madras Christian College",
        "location": "Guindy",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "common",
        "price": 5353,
        "distance": 1066
    },
    {
        "id": 73,
        "hostel_name": "Hillview Hostel",
        "vacancy": 12,
        "amenities": [
            "food",
            "kitchen",
            "wifi",
            "fridge",
            "ac",
            "laundry"
        ],
        "address": "176, Tambaram",
        "hostel_owner": "Ramesh",
        "contact_no": "9969186902",
        "nearby_university": "DG Vaishnav College",
        "location": "Adyar",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 6401,
        "distance": 1312
    },
    {
        "id": 74,
        "hostel_name": "Lakefront  Hostel",
        "vacancy": 15,
        "amenities": [
            "food",
            "ac",
            "wifi",
            "fitness centre",
            "fridge",
            "laundry"
        ],
        "address": "151, Saidapet",
        "hostel_owner": "Priya",
        "contact_no": "6837438752",
        "nearby_university": "DG Vaishnav College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 9815,
        "distance": 1126
    },
    {
        "id": 75,
        "hostel_name": "CoastalComfort Hostel",
        "vacancy": 20,
        "amenities": [
            "food",
            "study table",
            "laundry",
            "ac",
            "fitness centre"
        ],
        "address": "169, Teynampet",
        "hostel_owner": "Ramesh",
        "contact_no": "6869624419",
        "nearby_university": "DG Vaishnav College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 6431,
        "distance": 1410
    },
    {
        "id": 76,
        "hostel_name": "Riverstone  Hostel",
        "vacancy": 17,
        "amenities": [
            "kitchen",
            "food",
            "fridge",
            "wifi",
            "fitness centre"
        ],
        "address": "100, Porur",
        "hostel_owner": "Suresh",
        "contact_no": "7094881098",
        "nearby_university": "DG Vaishnav College",
        "location": "Adyar",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7821,
        "distance": 911
    },
    {
        "id": 77,
        "hostel_name": "GreenValley  Hostel",
        "vacancy": 23,
        "amenities": [
            "fridge",
            "kitchen",
            "fitness centre",
            "wifi",
            "ac",
            "food",
            "furniture",
            "laundry"
        ],
        "address": "82, Porur",
        "hostel_owner": "Ramesh",
        "contact_no": "8312949237",
        "nearby_university": "S.I.V.E.T College",
        "location": "Porur",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6785,
        "distance": 1703
    },
    {
        "id": 78,
        "hostel_name": "CentralNest Hostel",
        "vacancy": 5,
        "amenities": [
            "fridge",
            "kitchen",
            "laundry",
            "food",
            "ac"
        ],
        "address": "66, Adyar",
        "hostel_owner": "Vikram",
        "contact_no": "7973095094",
        "nearby_university": "S.I.V.E.T College",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "common",
        "price": 5899,
        "distance": 979
    },
    {
        "id": 79,
        "hostel_name": "Skyline  Hostel",
        "vacancy": 15,
        "amenities": [
            "fitness centre",
            "furniture",
            "fridge",
            "kitchen"
        ],
        "address": "115, Adyar",
        "hostel_owner": "Suresh",
        "contact_no": "9433284837",
        "nearby_university": "S.I.V.E.T College",
        "location": "Velachery",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 7661,
        "distance": 1459
    },
    {
        "id": 80,
        "hostel_name": "SouthSquare Hostel",
        "vacancy": 17,
        "amenities": [
            "kitchen",
            "ac",
            "laundry",
            "food",
            "fridge"
        ],
        "address": "169, Adyar",
        "hostel_owner": "Karthik",
        "contact_no": "6960711068",
        "nearby_university": "S.I.V.E.T College",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5455,
        "distance": 614
    },
    {
        "id": 81,
        "hostel_name": "EcoNest Hostel",
        "vacancy": 10,
        "amenities": [
            "fridge",
            "fitness centre",
            "ac",
            "study table",
            "laundry"
        ],
        "address": "109, Adyar",
        "hostel_owner": "Priya",
        "contact_no": "7268463251",
        "nearby_university": "New College",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 9374,
        "distance": 1608
    },
    {
        "id": 82,
        "hostel_name": "NatureHub Hostel",
        "vacancy": 22,
        "amenities": [
            "ac",
            "wifi",
            "fitness centre",
            "food",
            "laundry"
        ],
        "address": "37, Tambaram",
        "hostel_owner": "Karthik",
        "contact_no": "7057419215",
        "nearby_university": "New College",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 6308,
        "distance": 955
    },
    {
        "id": 83,
        "hostel_name": "BlueSky  Hostel",
        "vacancy": 19,
        "amenities": [
            "furniture",
            "study table",
            "kitchen",
            "ac",
            "food"
        ],
        "address": "154, Teynampet",
        "hostel_owner": "Priya",
        "contact_no": "9804550751",
        "nearby_university": "New College",
        "location": "Kodambakkam",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 8620,
        "distance": 1850
    },
    {
        "id": 84,
        "hostel_name": "Blossom  Hostel",
        "vacancy": 12,
        "amenities": [
            "furniture",
            "wifi",
            "laundry",
            "study table",
            "kitchen"
        ],
        "address": "92, Porur",
        "hostel_owner": "Ramesh",
        "contact_no": "6496451074",
        "nearby_university": "New College",
        "location": "Velachery",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 6409,
        "distance": 1161
    },
    {
        "id": 85,
        "hostel_name": "ForestDen Hostel",
        "vacancy": 16,
        "amenities": [
            "study table",
            "wifi",
            "food",
            "furniture"
        ],
        "address": "119, Saidapet",
        "hostel_owner": "Ramesh",
        "contact_no": "9707489257",
        "nearby_university": "M.O.P. Vaishnav College",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 5998,
        "distance": 1775
    },
    {
        "id": 86,
        "hostel_name": "GardenView Hostel",
        "vacancy": 14,
        "amenities": [
            "wifi",
            "furniture",
            "ac",
            "kitchen",
            "study table",
            "fridge"
        ],
        "address": "143, Saidapet",
        "hostel_owner": "Vikram",
        "contact_no": "6692652218",
        "nearby_university": "M.O.P. Vaishnav College",
        "location": "Teynampet",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 6465,
        "distance": 1010
    },
    {
        "id": 87,
        "hostel_name": "TerraHostel Hostel",
        "vacancy": 20,
        "amenities": [
            "study table",
            "ac",
            "food",
            "furniture",
            "laundry",
            "fitness centre",
            "wifi"
        ],
        "address": "172, Kodambakkam",
        "hostel_owner": "Suresh",
        "contact_no": "7515084919",
        "nearby_university": "M.O.P. Vaishnav College",
        "location": "Velachery",
        "type": "ladies",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 8219,
        "distance": 1008
    },
    {
        "id": 88,
        "hostel_name": "SpringHive Hostel",
        "vacancy": 9,
        "amenities": [
            "food",
            "fridge",
            "study table",
            "kitchen"
        ],
        "address": "109, Velachery",
        "hostel_owner": "Priya",
        "contact_no": "9330941342",
        "nearby_university": "M.O.P. Vaishnav College",
        "location": "Guindy",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 7559,
        "distance": 1243
    },
    {
        "id": 89,
        "hostel_name": "LeafyLodge Hostel",
        "vacancy": 17,
        "amenities": [
            "kitchen",
            "furniture",
            "study table",
            "fridge",
            "food",
            "wifi",
            "laundry"
        ],
        "address": "51, Tambaram",
        "hostel_owner": "Ramesh",
        "contact_no": "9862850902",
        "nearby_university": "SRM Easwari Engineering College",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5781,
        "distance": 829
    },
    {
        "id": 90,
        "hostel_name": "ZenithStay Hostel",
        "vacancy": 17,
        "amenities": [
            "laundry",
            "wifi",
            "furniture",
            "kitchen",
            "study table",
            "ac",
            "fridge",
            "fitness centre"
        ],
        "address": "149, Tambaram",
        "hostel_owner": "Suresh",
        "contact_no": "7679670763",
        "nearby_university": "SRM Easwari Engineering College",
        "location": "Porur",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 5129,
        "distance": 1131
    },
    {
        "id": 91,
        "hostel_name": "EliteNest Hostel",
        "vacancy": 23,
        "amenities": [
            "study table",
            "fridge",
            "laundry",
            "fitness centre"
        ],
        "address": "140, Tambaram",
        "hostel_owner": "Vikram",
        "contact_no": "6892545914",
        "nearby_university": "SRM Easwari Engineering College",
        "location": "Adyar",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 9582,
        "distance": 1554
    },
    {
        "id": 92,
        "hostel_name": "AxisLodge Hostel",
        "vacancy": 9,
        "amenities": [
            "ac",
            "wifi",
            "laundry",
            "fitness centre",
            "fridge",
            "study table",
            "furniture",
            "food"
        ],
        "address": "26, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "7675473820",
        "nearby_university": "SRM Easwari Engineering College",
        "location": "Saidapet",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "common",
        "price": 5736,
        "distance": 1431
    },
    {
        "id": 93,
        "hostel_name": "VibeSpace Hostel",
        "vacancy": 8,
        "amenities": [
            "laundry",
            "furniture",
            "fitness centre",
            "study table",
            "fridge",
            "kitchen",
            "wifi",
            "food"
        ],
        "address": "191, Velachery",
        "hostel_owner": "Vikram",
        "contact_no": "6957774086",
        "nearby_university": "Dr. M.G.R. Educational and Research Institute",
        "location": "Adyar",
        "type": "ladies",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 7843,
        "distance": 793
    },
    {
        "id": 94,
        "hostel_name": "UrbanEdge Hostel",
        "vacancy": 23,
        "amenities": [
            "ac",
            "fridge",
            "study table",
            "fitness centre"
        ],
        "address": "76, Velachery",
        "hostel_owner": "Karthik",
        "contact_no": "7697577595",
        "nearby_university": "Dr. M.G.R. Educational and Research Institute",
        "location": "Tambaram",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5104,
        "distance": 1304
    },
    {
        "id": 95,
        "hostel_name": "CoreHostel Hostel",
        "vacancy": 24,
        "amenities": [
            "study table",
            "wifi",
            "kitchen",
            "ac",
            "fridge",
            "food"
        ],
        "address": "170, Tambaram",
        "hostel_owner": "Priya",
        "contact_no": "7379615295",
        "nearby_university": "Dr. M.G.R. Educational and Research Institute",
        "location": "Velachery",
        "type": "ladies",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7033,
        "distance": 1567
    },
    {
        "id": 96,
        "hostel_name": "NovaRoom Hostel",
        "vacancy": 6,
        "amenities": [
            "wifi",
            "fridge",
            "laundry",
            "study table"
        ],
        "address": "45, Kodambakkam",
        "hostel_owner": "Priya",
        "contact_no": "6358036690",
        "nearby_university": "Dr. M.G.R. Educational and Research Institute",
        "location": "Guindy",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 7308,
        "distance": 1762
    },
    {
        "id": 97,
        "hostel_name": "ModuStay Hostel",
        "vacancy": 12,
        "amenities": [
            "ac",
            "fridge",
            "laundry",
            "study table",
            "furniture"
        ],
        "address": "126, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "9964026616",
        "nearby_university": "Siva Subramaniya Nadar College",
        "location": "Teynampet",
        "type": "gents",
        "room_type": "double",
        "bathroom_type": "attached",
        "price": 7417,
        "distance": 1457
    },
    {
        "id": 98,
        "hostel_name": "Clarity  Hostel",
        "vacancy": 10,
        "amenities": [
            "food",
            "study table",
            "laundry",
            "furniture",
            "ac",
            "fridge",
            "wifi",
            "fitness centre"
        ],
        "address": "95, Guindy",
        "hostel_owner": "Priya",
        "contact_no": "9091679173",
        "nearby_university": "Siva Subramaniya Nadar College",
        "location": "Tambaram",
        "type": "gents",
        "room_type": "triple",
        "bathroom_type": "attached",
        "price": 5301,
        "distance": 748
    },
    {
        "id": 99,
        "hostel_name": "Drift  Hostel",
        "vacancy": 18,
        "amenities": [
            "food",
            "laundry",
            "study table",
            "kitchen"
        ],
        "address": "172, Guindy",
        "hostel_owner": "Ramesh",
        "contact_no": "6595194055",
        "nearby_university": "Siva Subramaniya Nadar College",
        "location": "Kodambakkam",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 5310,
        "distance": 1280
    },
    {
        "id": 100,
        "hostel_name": "Nomad's Pad Hostel",
        "vacancy": 17,
        "amenities": [
            "wifi",
            "food",
            "laundry",
            "fitness centre"
        ],
        "address": "5, Kodambakkam",
        "hostel_owner": "Priya",
        "contact_no": "9676277866",
        "nearby_university": "Siva Subramaniya Nadar College",
        "location": "Velachery",
        "type": "gents",
        "room_type": "single",
        "bathroom_type": "attached",
        "price": 7451,
        "distance": 589
    }
]

result = hostel_collection.insert_many(hostels)
print(f"{len(result.inserted_ids)} hostels inserted successfully.")